---
- hosts: diplo_vm1
  become: yes
  remote_user: admindiplo
  become_user: root
  tasks:  
  
  - name: Instala Java 11
    ansible.builtin.yum:
      name: java-11-openjdk-devel
      state: present
  - name: Copia script para repositorio Jenkins
    copy: src=./repos.sh dest=/tmp mode=700
  - name: Ejecuta script para repositorio Jenkins
    command: sh /tmp/repos.sh
  - name: Instala Jenkins
    ansible.builtin.yum:
      name: jenkins
  - name: Configuracion de servicio
    ansible.builtin.systemd:
      daemon_reload: yes
  - name: Inicia Jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
  - name: Abre puerto para Jenkins
    ansible.posix.firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
  - name: Reinicia firewalld
    ansible.builtin.systemd:
      name: firewalld
      state: restarted

